# Generated by Django 4.0.2 on 2022-02-10 06:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_outlet_label_outlet_name_alter_employee_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outlet',
            name='name',
        ),
        migrations.AddField(
            model_name='outlet',
            name='label',
            field=models.CharField(default='label', max_length=100),
        ),
        migrations.AlterField(
            model_name='visit',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 2, 10, 6, 45, 40, 395203, tzinfo=utc)),
        ),
    ]
