# Generated by Django 4.0.2 on 2022-02-10 07:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_outlet_name_outlet_label_alter_visit_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 2, 10, 7, 3, 45, 181723, tzinfo=utc)),
        ),
    ]
