# Generated by Django 4.0.2 on 2022-02-10 07:21

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_employee_phone_number_alter_visit_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 2, 10, 7, 21, 7, 662773, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='visit',
            name='visit_outlet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outlets_visit', to='app.outlet'),
        ),
    ]
